name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - uses: actions/checkout@v4

      # Step 2: Set Python path (ensure that the root directory is included in the Python path)
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Add root directory to the path

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Use the correct Python version here

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage  # Install pytest and coverage to generate coverage reports

      # Step 5: Install unzip and SonarScanner
      - name: Install unzip and SonarScanner
        run: |
          # Install unzip (if it's not installed)
          sudo apt-get install -y unzip
          
          # Download SonarScanner
          wget https://github.com/SonarSource/sonar-scanner-cli/archive/refs/tags/7.0.2.4839.zip

          # Unzip the downloaded file
          unzip 7.0.2.4839.zip

          mv sonar-scanner-cli-7.0.2.4839 sonar-scanner

          # List the contents of the directory to confirm sonar-scanner is extracted
          ls -alh sonar-scanner
          
          # Make sure the sonar-scanner is executable
          chmod +x sonar-scanner/bin/sonar-scanner

          # Add SonarScanner to PATH
          echo "SONAR_SCANNER_HOME=$PWD/sonar-scanner" >> $GITHUB_ENV
          echo "PATH=$PWD/sonar-scanner/bin:$PATH" >> $GITHUB_ENV

          # Verify sonar-scanner is executable
          sonar-scanner --version

      # Step 6: Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q  # Run tests in the 'tests' directory
          coverage run -m pytest  # Run coverage with pytest
          coverage xml  # Generates the coverage.xml file

      # Step 7: Run SonarCloud analysis
      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Reference the token from GitHub secrets
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Kavana179_python-Calculator \
            -Dsonar.organization=kavana179 \
            -Dsonar.sources=.  # Root directory as the source
            -Dsonar.language=python  # Specify the language as Python
            -Dsonar.python.version=3.9  # Specify the exact Python version
            -Dsonar.python.coverage.reportPaths=coverage.xml  # Point to the generated coverage report
