name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full clone for better analysis relevancy

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the appropriate version of Python (e.g., 3.8, 3.9, etc.)

      # Step 3: Cache Python dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip

      # Step 4: Install dependencies (manually install the packages)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage  # Add any other dependencies you need

      # Step 5: Run tests (optional, depending on your test framework)
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Step 6: SonarCloud Scan
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar.organization: kavana179
          sonar.projectKey: Kavana179_python-Calculator
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
