name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # You can update this version to your required Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Install pytest and coverage tools
    - name: Install pytest and coverage
      run: |
        pip install pytest pytest-cov

    # Step 5: Run tests and generate code coverage report
    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q --cov=calculator --cov-report=xml  # Ensure your package name matches

    # Step 6: Install SonarCloud Scanner
    - name: Install SonarCloud Scanner
      run: |
        pip install sonar-scanner

    # Step 7: Run SonarCloud Analysis
    - name: Run SonarCloud Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Make sure SONAR_TOKEN is stored in GitHub Secrets
      run: |
        sonar-scanner \
          -Dsonar.projectKey=Kavana179_python-Calculator \
          -Dsonar.organization=kavana179 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.python.coverage.reportPaths=coverage.xml  # Path to the coverage report generated by pytest

